export const siteConfig = {
  name: "DankDealsMN - Premium Cannabis Delivery in Minneapolis",
  description:
    "Explore our showcase of premium cannabis products. Your trusted source for THC delivery and cannabis in Minneapolis & St. Paul. Text to order at (612) 930-1390.",
  url: "https://dankdealsmn.com",
  keywords: [
    "THC delivery Minneapolis",
    "Weed delivery St. Paul",
    "Cannabis delivery Twin Cities",
    "Cannabis Minnesota",
    "Text to order weed",
    "Cannabis gifting",
    "Marijuana delivery",
    "Minnesota cannabis",
    "Minneapolis dispensary",
    "St. Paul dispensary",
    "Twin Cities dispensary",
    "Minnesota dispensary",
    "Cannabis dispensary near me",
    "Weed dispensary Minneapolis",
    "THC dispensary Minnesota",
    "Medical marijuana dispensary",
    "Recreational dispensary Minneapolis",
    "Local dispensary Twin Cities",
    "Best dispensary Minneapolis",
    "Cannabis dispensary St. Paul",
    "Marijuana dispensary Minnesota",
    "Online dispensary Minnesota",
    "Cannabis store Minneapolis",
    "Weed shop Twin Cities",
    "Dispensary delivery Minneapolis",
    "Legal dispensary Minnesota",
    "Licensed dispensary Twin Cities",
    "Premium dispensary Minneapolis",
    "Cannabis retail Minnesota",
    "Marijuana store Minneapolis",
    "THC shop St. Paul",
    "Adult use dispensary Minnesota",
    "Cannabis outlet Twin Cities",
  ],
}
